### ISSUE TITLE
Have UI connect to backend that insert into spreadsheet

### ISSUE THREAD

**Issue by calvinbrown085** [ethanphunter/PointOfSaleProject#16]

**Comment by ethanphunter** [comment]
@calvinbrown085 What is this for? Is it supposed to be some dev ui?

**Comment by calvinbrown085** [comment]
@ethanphunter Sorry i didn't see your comment, basically to have a user interface for inserting into the spreadsheet

**Comment by ethanphunter** [comment]
@calvinbrown085 But would this be something only the manager would be able to use, or something that only someone with dev creds can use?

**Comment by calvinbrown085** [comment]
@ethanphunter I'm closing this
